import { NextComponentType, type NextPage } from "next";
import Head from "next/head";
import Main from "../components/main";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Track your habits</title>
        <meta name="description" content="Generated by pr31nis" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main></Main>
    </>
  );
};

export default Home;
